### ISSUE TITLE
My Bookings and Manage Booking is not displayed correctly

### ISSUE THREAD

**Issue by jawsvk** [natebakescakes/team11-cab#32]
My bookings does not display

**Comment by natebakescakes** [comment]
If Manage Booking has an error it's probably data related. Mine was broken because a UserId was null in the DB. Probably due to erroneous booking submission.

**Comment by natebakescakes** [comment]
My bookings JSP page and corresponding JS file must match number of headers.

**Comment by jawsvk** [comment]
![image](https://user-images.githubusercontent.com/36097628/41495144-ec3f42ca-7152-11e8-93f3-2d29fca8cf77.png)

this worked for me
