### ISSUE TITLE
Not selecting date on Homepage on booking search will cause page to break

### ISSUE THREAD

**Issue by natebakescakes** [natebakescakes/team11-cab#37]
Replicate using following steps:

1. Navigate to Homepage
2. Select Facility, time range, leave date blank
3. Click 'Submit' button

![image](https://user-images.githubusercontent.com/12733264/41460651-0283b7c0-70c0-11e8-9ac2-e826339eb211.png)

![image](https://user-images.githubusercontent.com/12733264/41460672-0c538410-70c0-11e8-8428-a3858440dd01.png)

**Comment by jawsvk** [comment]
will put an validation check on booking controller, if either facility type or date is not selected, error message will appear next to homepage submit button
